services:
  - type: web
    name: fashion-sat-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 webapp.py
    envVars:
      - key: FLASK_ENV
        value: production
